trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: MacBuild
  displayName: Mac Build
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Release:
        B_BUILD_TYPE: Release
        BARRIER_VERSION_STAGE: Release
  steps:
    - script: brew info openssl
      displayName: show openssl info
    - script: sudo xcode-select -s /Applications/Xcode_10.app/Contents/Developer
      displayName: Select older Xcode
    - script: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aac86fc018c48d7b6f23a2e7535276899774567a/Formula/qt.rb
      displayName: Installed Pinned Qt
    - script: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aac86fc018c48d7b6f23a2e7535276899774567a/Formula/openssl.rb
      displayName: Installed Pinned OpenSSL
    - script: QT_PATH=/usr/local/opt/qt/bin CMAKE_OSX_DEPLOYMENT_TARGET=10.14 CMAKE_OSX_ARCHITECTURES=x86_64 sh -x ./clean_build.sh
      displayName: Clean Build
    - task: PublishBuildArtifacts@1
      displayName: Publish Release DMG
      condition: eq(variables['B_BUILD_TYPE'], 'Release')
      inputs:
        pathtoPublish: build/bundle
        artifactName: Mac Release Disk Image and App
