trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: MacBuild
  displayName: Mac Build
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Release:
        B_BUILD_TYPE: Release
        BARRIER_VERSION_STAGE: Release
  steps:
    - script: |
        ls -l /usr/local/opt
        rm -rf /usr/local/opt/openssl
        brew reinstall openssl
        ls -l /usr/local/opt
      displayName: Show /usr/local/opt contents before and after removing 1.0.2t