trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: MacBuild
  displayName: Mac Build
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Release:
        B_BUILD_TYPE: Release
        BARRIER_VERSION_STAGE: Release
  steps:
    - script: brew install pkg-config openssl qt5
      displayName: Installed prereqs
    - script: PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH pkg-config --libs openssl
      displayName: add openssl pkg config path
    - script: QT_PATH=/usr/local/opt/qt/bin CMAKE_OSX_DEPLOYMENT_TARGET=10.14 CMAKE_OSX_ARCHITECTURES=x86_64 sh -x ./clean_build.sh
      displayName: Clean Build
    - script: pkg-config --libs openssl
      displayName: print openssl libs2
    - task: PublishBuildArtifacts@1
      displayName: Publish Release DMG
      condition: eq(variables['B_BUILD_TYPE'], 'Release')
      inputs:
        pathtoPublish: build/bundle
        artifactName: Mac Release Disk Image and App
