trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: MacBuild
  displayName: Mac Build
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Release:
        B_BUILD_TYPE: Release
        BARRIER_VERSION_STAGE: Release
  steps:
    - script: uname -a
      displayName: uname
    - script: brew install qt5 pkg-config
      displayName: Installed Qt
    - script: |
        export OPENSSL_ROOT="/usr/local/opt/openssl@1.1/"
        export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
        export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
        export CFLAGS="-I/usr/local/opt/openssl@1.1/include"
        export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
        sh -x ./clean_build.sh
      displayName: Clean Build
    - task: PublishBuildArtifacts@1
      displayName: Publish Release DMG
      condition: eq(variables['B_BUILD_TYPE'], 'Release')
      inputs:
        pathtoPublish: build/bundle
        artifactName: Mac Release Disk Image and App
